name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:
  MONGO_URI: mongodb://mongoadmin:secret@mongodb:27017
  MONGO_USERNAME: mongoadmin 
  MONGO_PASSWORD: secret 

jobs:
  unit-testing:
    name: Unit Testing
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        env:
          MONGO_INITDB_ROOT_PASSWORD: ${{ env.MONGO_PASSWORD }}
          MONGO_INITDB_ROOT_USERNAME: ${{ env.MONGO_USERNAME }}
        ports:
          - 27017:27017
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup NodeJS Version
      uses: actions/setup-node@v3
      with:
        node-version: 20
    
    - name: Wait for MongoDB to be Ready
      run: |
        for i in {1..10}; do
          nc -z mongodb 27017 && echo "MongoDB is ready" && exit 0
          echo "Waiting for MongoDB..."
          sleep 5
        done
        echo "MongoDB did not become ready in time" && exit 1
    
    - name: Install Dependencies
      run: npm install
    
    - name: Unit Testing
      env:
        MONGO_URI: ${{ env.MONGO_URI }}
      run: npm test
          
    - name: Archive Test Result
      uses: actions/upload-artifact@v4
      with:
        name: Mocha-Test-Result
        path: test-results.xml